# Generated by Django 4.2 on 2025-01-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('events', models.ManyToManyField(related_name='players', to='sports.event')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sports.nation')),
                ('sports', models.ManyToManyField(related_name='players', to='sports.sport')),
            ],
        ),
    ]
