# Generated by Django 4.2 on 2025-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='player',
            field=models.ManyToManyField(related_name='events', to='sports.player'),
        ),
    ]
