# Generated by Django 4.2 on 2025-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_remove_player_events_event_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nation',
            field=models.ManyToManyField(blank=True, related_name='events', to='sports.nation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='events', to='sports.player'),
        ),
    ]
