# Generated by Django 4.2 on 2025-01-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='first_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='second_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
