# Generated by Django 4.2 on 2025-01-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_cart_remove_ticket_qr_code'),
        ('panier', '0002_alter_cart_first_key_alter_cart_second_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tickets',
            field=models.ManyToManyField(related_name='carts', to='ticket.ticket'),
        ),
    ]
