# Generated by Django 4.2 on 2025-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticket_stadium_ticket_event_alter_ticket_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
