# Generated by Django 4.2 on 2025-01-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_nbr_place_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
    ]
